# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2014-05-08 13:49+BRT\n"
"PO-Revision-Date: 2014-05-08 13:50-0300\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: UTF-8\n"
"Generated-By: pygettext.py 1.5\n"


#: controller/__data__.py:7
msgid "ERROR: Cannot detect installed system, impossible to upgrade"
msgstr ""
"ОШИБКА: Не обнаружена установленная система - обновление невозможно"

#: controller/__data__.py:8
msgid "ERROR: Cannot detect installed system version, impossible to upgrade"
msgstr ""
"ОШИБКА: Не обнаружена версия установленной системы - обновление невозможно"

#: controller/__data__.py:9
msgid "ERROR: Cannot fast forward upgrades, impossible to upgrade"
msgstr ""
"ОШИБКА: Не удалось выполнить быструю перемотку обновлений - обновление невозможно"

#: controller/__data__.py:10
msgid "ERROR: Installed system is newer, impossible to upgrade"
msgstr ""
"ОШИБКА: Установленная система новее - обновление невозможно"

#: controller/__data__.py:11
msgid "ERROR: Upgrade failed."
msgstr ""
"ОШИБКА: Сбой обновления."

#: controller/__data__.py:12
msgid "Error while installing IBM PowerKVM into disk %s"
msgstr ""
"Ошибка установки IBM PowerKVM на диск %s"

#: controller/__data__.py:13
msgid "Formatting disks..."
msgstr ""
"Форматирование дисков..."

#: controller/__data__.py:14
msgid "Formatting root device to reinstall system"
msgstr ""
"Форматирование корневого устройства для переустановки системы"

#: controller/__data__.py:15
msgid "Installing IBM PowerKVM into disk %s..."
msgstr ""
"Установка IBM PowerKVM на диск %s..."

#: controller/__data__.py:16
msgid "Install IBM PowerKVM"
msgstr ""
"Установить IBM PowerKVM"

#: controller/__data__.py:17
msgid "Proceed to upgrade the system?"
msgstr ""
"Перейти к обновлению системы?"

#: controller/__data__.py:18
msgid "Reinstall IBM PowerKVM"
msgstr ""
"Переустановить IBM PowerKVM"

#: controller/__data__.py:19
msgid "Rescue mode (goes to terminal)"
msgstr ""
"Режим аварийного восстановления (переход в терминал)"

#: controller/__data__.py:20
msgid "Running Post Upgrade Scripts"
msgstr ""
"Выполнение заключительных сценариев обновления"

#: controller/__data__.py:21
msgid "System Installed. Starting post install scripts."
msgstr ""
"Система установлена. Выполнение заключительных сценариев установки."

#: controller/__data__.py:22
msgid "Upgrade concluded!"
msgstr ""
"Обновление завершено!"

#: controller/__data__.py:23
msgid "Upgrade installed IBM PowerKVM"
msgstr ""
"Обновить установленный IBM PowerKVM"

#: controller/__data__.py:24
msgid "Getting disk information..."
msgstr ""
"Получение информации о дисках..."

#: ui/__data__.py:6 viewer/__data__.py:36
msgid "Root Password"
msgstr ""
"Пароль пользователя root"

#: ui/__data__.py:7
msgid "Timezone selection"
msgstr ""
"Выбор часового пояса"

#: ui/__data__.py:8
msgid "Date and Time"
msgstr ""
"Дата и время"

#: ui/__data__.py:9
msgid "Configure Network"
msgstr ""
"Настроить сеть"

#: ui/__data__.py:10
msgid "DNS configuration"
msgstr ""
"Конфигурация DNS"

#: ui/__data__.py:11
msgid "Exit"
msgstr ""
"Выход"

#: viewer/__data__.py:12
msgid "Welcome to IBM PowerKVM %s"
msgstr ""
"Вас приветствует IBM PowerKVM %s"

#: viewer/__data__.py:13
msgid "Select one of the options below and follow the instructions."
msgstr ""
"Выберите одну из следующих опций внизу и следуйте инструкциям."

#: viewer/__data__.py:14
msgid ""
"Are you sure you want to install on device %s?\n\n The following partitions will be removed: %s\n\n The following LVMs will be removed: %s\n\n"
msgstr ""
"Вы действительно хотите выполнить установку на устройство %s?\n\n Будут удалены следующие разделы: %s\n\n Будут удалены следующие LVM: %s\n\n"

#: viewer/__data__.py:17
msgid "IBM PowerKVM %s"
msgstr ""
"IBM PowerKVM %s"

#: viewer/__data__.py:18
msgid "Ok"
msgstr ""
"OK"

#: viewer/__data__.py:19
msgid "Back"
msgstr ""
"Назад"

#: viewer/__data__.py:20
msgid "Skip"
msgstr ""
"Пропустить"

#: viewer/__data__.py:21
msgid "Next"
msgstr ""
"Далее"

#: viewer/__data__.py:22
msgid "Edit"
msgstr ""
"Изменить"

#: viewer/__data__.py:23
msgid "  <Tab>/<Shift-Tab> between elements   |  <Space> selects"
msgstr ""
"  <Tab>/<Shift-Tab> - переход по элементам   |  <Пробел> - выбор"

#: viewer/__data__.py:29
msgid "Password Length"
msgstr ""
"Длина пароля"

#: viewer/__data__.py:30
msgid "The root password must be at least 6 characters long."
msgstr ""
"Пароль пользователя root должен быть не короче 6 символов."

#: viewer/__data__.py:31
msgid "Password Mismatch"
msgstr ""
"Пароли не совпадают"

#: viewer/__data__.py:32
msgid "The passwords you entered were different. Please try again."
msgstr ""
"Введенные пароли не совпадают. Повторите ввод."

#: viewer/__data__.py:33
msgid "Password (confirm):"
msgstr ""
"Пароль (подтверждение):"

#: viewer/__data__.py:34
msgid "Password:"
msgstr ""
"Пароль:"

#: viewer/__data__.py:35
msgid "Pick a root password. You must type it twice to ensure you know what it is and didn't make a mistake in typing. Remember that the root password is a critical part of system security!"
msgstr ""
"Выберите пароль пользователя root. Его необходимо ввести дважды, чтобы исключить опечатки. Помните, что пароль пользователя root - важная часть защиты системы!"

#: viewer/__data__.py:41
msgid "Select the timezone for the system"
msgstr ""
"Выберите часовой пояс для системы"

#: viewer/__data__.py:42
msgid "System clock uses UTC"
msgstr ""
"Системные часы используют UTC"

#: viewer/__data__.py:43
msgid "Timezone Selection"
msgstr ""
"Выбор часового пояса"

#: viewer/__data__.py:48
msgid "Select the device to be configured:"
msgstr ""
"Выберите устройство для настройки:"

#: viewer/__data__.py:49
msgid "Configure network"
msgstr ""
"Настроить сеть"

#: viewer/__data__.py:50
msgid "UP"
msgstr ""
"Вверх"

#: viewer/__data__.py:51
msgid "DOWN"
msgstr ""
"Вниз"

#: viewer/__data__.py:56
msgid "Hostname"
msgstr ""
"Имя хоста"

#: viewer/__data__.py:57
msgid "Primary DNS"
msgstr ""
"Первичный DNS"

#: viewer/__data__.py:58
msgid "Secondary DNS"
msgstr ""
"Вторичный DNS"

#: viewer/__data__.py:59
msgid "Search"
msgstr ""
"Поиск"

#: viewer/__data__.py:60
msgid "DNS Configuration"
msgstr ""
"Конфигурация DNS"

#: viewer/__data__.py:65
msgid "NTP Configuration"
msgstr ""
"Конфигурация NTP"

#: viewer/__data__.py:66
msgid "NTP server 1: "
msgstr ""
"Сервер NTP 1: "

#: viewer/__data__.py:67
msgid "NTP server 2: "
msgstr ""
"Сервер NTP 2: "

#: viewer/__data__.py:68
msgid "NTP server 3: "
msgstr ""
"Сервер NTP 3: "

#: viewer/__data__.py:69
msgid "NTP server 4: "
msgstr ""
"Сервер NTP 4: "

#: viewer/__data__.py:70
msgid "Enable"
msgstr ""
"Включить"

#: viewer/__data__.py:75
msgid "Date and time configuration"
msgstr ""
"Настройка даты и времени"

#: viewer/__data__.py:76
msgid "Date (YYYY / MM / DD):"
msgstr ""
"Дата (ГГГГ / ММ / ДД):"

#: viewer/__data__.py:77
msgid "Time (HH:MM:SS):"
msgstr ""
"Время (ЧЧ:ММ:СС):"

#: viewer/__data__.py:78
msgid "Date time error"
msgstr ""
"Ошибка даты или времени"

#: viewer/__data__.py:79
msgid ""
"Date or time format is not correct!\nThe input: %s\nCorrect format: YYYY/MM/DD HH:MM:SS"
msgstr ""
"Неправильный формат даты или времени!\nУказано: %s\nПравильный формат: ГГГГ/ММ/ДД ЧЧ:ММ:СС"

#: viewer/__data__.py:85
msgid "Invalid Entry"
msgstr ""
"Недопустимая запись"

#: viewer/__data__.py:86
msgid "Either DHCP must be selected, or IP must be provided."
msgstr ""
"Требуется выбрать DHCP или указать IP-адрес."

#: viewer/__data__.py:87
msgid "Device"
msgstr ""
"Устройство"

#: viewer/__data__.py:88
msgid "MAC Address"
msgstr ""
"MAC-адрес"

#: viewer/__data__.py:89
msgid "Use DHCP"
msgstr ""
"Использовать DHCP"

#: viewer/__data__.py:90
msgid "Static IP"
msgstr ""
"Статический IP-адрес"

#: viewer/__data__.py:91
msgid "Netmask"
msgstr ""
"Маска сети"

#: viewer/__data__.py:92
msgid "Default gateway IP"
msgstr ""
"IP-адрес шлюза по умолчанию"

#: viewer/__data__.py:93
msgid "Network Device Configuration"
msgstr ""
"Конфигурация сетевых устройств"

#: viewer/__data__.py:94
msgid "Create Network bridge device (br%s)"
msgstr ""
"Создать устройство сетевого моста (br%s)"

#: viewer/__data__.py:98
msgid "Error while trying to remove the Volume Group in %s"
msgstr ""
"Ошибка удаления группы томов в %s"

#: viewer/__data__.py:99
msgid "The disk %s is part of the LVM Volume Group(s) ['VolGroup'] which will be destroyed if you continue. Are you sure you want to use that disk?"
msgstr ""
"Диск %s - часть группы томов LVM ['VolGroup']. Если продолжить, группа будет уничтожена. Вы действительно хотите использовать этот диск?"

#: viewer/__data__.py:100
msgid "Yes"
msgstr ""
"Да"

#: viewer/__data__.py:101
msgid "No"
msgstr ""
"Нет"

#: viewer/__data__.py:102
msgid "Installation Error"
msgstr ""
"Ошибка установки"

#: viewer/__data__.py:107
msgid "Select the device to install IBM PowerKVM. All data in the selected disk will be lost."
msgstr ""
"Выберите устройство для установки IBM PowerKVM. Все данные на выбранном диске будут потеряны."

#: viewer/__data__.py:108
msgid "Disk information"
msgstr ""
"Информация о диске"

#: viewer/__data__.py:109
msgid "  <Tab>/<Shift-Tab> between elements  |  <F3> for details"
msgstr ""
"  <Tab>/<Shift-Tab> - переход по элементам  |  <F3> - сведения"

#: viewer/__data__.py:110
msgid "Disk size"
msgstr ""
"Размер диска"

#: viewer/__data__.py:111
msgid "The disk size must be greater than 70G!"
msgstr ""
"Размер диска должен быть больше 70 ГБ!"

#: viewer/__data__.py:112
msgid "No disk found"
msgstr ""
"Диски не найдены"

#: viewer/__data__.py:113
msgid "No disks were found in the system."
msgstr ""
"В системе не найдены диски."

#: viewer/__data__.py:114
msgid "ID:"
msgstr ""
"ИД:"

#: viewer/__data__.py:115
msgid "Size"
msgstr ""
"Размер"

#: viewer/__data__.py:116
msgid "Multipath:"
msgstr ""
"С несколькими путями:"

#: viewer/__data__.py:117
msgid "Name"
msgstr ""
"Имя"

#: viewer/__data__.py:118
msgid "Filesystem"
msgstr ""
"Файловая система"

#: viewer/__data__.py:119
msgid "VG/Raid"
msgstr ""
"Группа томов/массив"

#: viewer/__data__.py:125
msgid "Choose the language"
msgstr ""
"Выберите язык"

#: viewer/__data__.py:130
msgid "The current installed system will be erased, including all general system-wide and virtualization configuration files.Only the contents within /var/lib/libvirt/images and /var/log will be preserved. WARNING: this means the configuration of your Virtual Machines WILL BE ERASED, leaving only the disk images behind. You are advised to back up your VM configurations before proceeding. Are you sure you would like to proceed?"
msgstr ""
"Установленная система будет стерта, включая все общесистемные файлы и настройки виртуализации. Сохранится только содержимое каталогов /var/lib/libvirt/images и /var/log. ПРЕДУПРЕЖДЕНИЕ: конфигурации виртуальных машин будут УНИЧТОЖЕНЫ, останутся только образы дисков. Перед продолжением рекомендуется создать резервные копии ВМ. Продолжить?"

#: viewer/__data__.py:136
msgid ""
"A previous installation of PowerKVM has been detected at:\n"
"\n"
"%s\n"
"\n"
msgstr ""
"Предыдущая установленная копия PowerKVM обнаружена в:\n"
"\n"
"%s\n"
"\n"

#: viewer/__data__.py:141
msgid "Hardware is not entitled to proceed. Aborting!"
msgstr ""
"Не выделено аппаратное обеспечение для продолжения. Выход!"

#: viewer/__data__.py:142
msgid "Invalid entitlement! "
msgstr ""
"Недопустимое выделение! "

#: viewer/__data__.py:147
msgid "Preparing to install IBM PowerKVM System"
msgstr ""
"Подготовка IBM PowerKVM System к установке"

#: viewer/__data__.py:148
msgid "Unknown error"
msgstr ""
"Неизвестная ошибка"

#: viewer/__data__.py:149
msgid "Sorry something went wrong the proper error message is on the log file"
msgstr ""
"Что-то пошло не так. См. сообщение об ошибке в файле протокола"

#: viewer/__data__.py:155
msgid "Please, reboot your system now."
msgstr ""
"Перезагрузите систему."

#: viewer/__data__.py:156
msgid "Reboot"
msgstr ""
"Перезагрузить"

#: viewer/__data__.py:157
msgid "Installation completed! "
msgstr ""
"Установка завершена! "

#: viewer/__data__.py:162
msgid "The reinstall process can't continue. No previous system was found. Aborting!"
msgstr ""
"Продолжение процесса переустановки невозможно. Не найдена предыдущая система. Выход!"

#: viewer/__data__.py:168
msgid "Preparing to upgrade system"
msgstr ""
"Подготовка к обновлению системы"

#: viewer/__data__.py:169
msgid "Working..."
msgstr ""
"Выполняется..."

#: viewer/__data__.py:174
msgid "Installation exited with error code: %s"
msgstr ""
"Установка завершена с кодом ошибки %s"

#: viewer/__data__.py:175
msgid "Log is available on %s"
msgstr ""
"Протокол доступен в %s"

#: viewer/__data__.py:176
msgid "Unexpected error."
msgstr ""
"Непредвиденная ошибка."

#: viewer/__data__.py:177
msgid "Unknown error."
msgstr ""
"Неизвестная ошибка."

#: viewer/__data__.py:178
msgid "Invalid disk size."
msgstr ""
"Недопустимый размер диска."

#: viewer/__data__.py:179
msgid "No disk found in the system."
msgstr ""
"В системе не найдены диски."

#: viewer/__data__.py:180
msgid "Hardware is not entitled, aborting installation."
msgstr ""
"Не выделено аппаратное обеспечение, установка завершается."

#: viewer/__data__.py:181
msgid "Error while installing IBM PowerKVM."
msgstr ""
"Ошибка при установке IBM PowerKVM."

#: viewer/__data__.py:182
msgid "Error while performing disk operations."
msgstr ""
"Ошибка при выполнении дисковых операций."

#: viewer/__data__.py:183
msgid "Invalid error code."
msgstr ""
"Недопустимый код ошибки."

#: viewer/__data__.py:184
msgid "Could not remove LVM entities."
msgstr ""
"Не удалось удалить объекты LVM."

#: viewer/__data__.py:185
msgid "Could not deactivate volume groups."
msgstr ""
"Не удалось деактивировать группы томов."

#: viewer/__data__.py:186
msgid "Could not activate volume groups."
msgstr ""
"Не удалось активировать группы томов."

#: viewer/__data__.py:187
msgid "Could not stop software RAID."
msgstr ""
"Не удалось остановить программный RAID."

#: viewer/__data__.py:188
msgid "Disk information not available."
msgstr ""
"Информация о диске недоступна."

#: viewer/__data__.py:189
msgid "Problem while removing pratitioning scheme."
msgstr ""
"Неполадка при удалении схемы создания разделов."

#: viewer/__data__.py:190
msgid "Problem while partitioning the disk."
msgstr ""
"Неполадка при создании разделов диска."

#: viewer/__data__.py:191
msgid "Problem while creating LVM."
msgstr ""
"Неполадка при создании LVM."

#: viewer/__data__.py:192
msgid "Failed to download (HTTP) install automation file."
msgstr ""
"Не удалось загрузить файл автоматизации установки (HTTP)."

#: viewer/__data__.py:193
msgid "Failed to download (TFTP) install automation file."
msgstr ""
"Не удалось загрузить файл автоматизации установки (TFTP)."

#: viewer/__data__.py:194
msgid "Problem downloading (NFS) install automation file."
msgstr ""
"Не удалось загрузить файл автоматизации установки (NFS)."

#: viewer/__data__.py:195
msgid "Could not parse install automation file."
msgstr ""
"Не удалось проанализировать файл автоматизации установки."

#: viewer/__data__.py:196
msgid "Failed to get IPR RAID label."
msgstr ""
"Не удалось получить метку IPR RAID."

#: viewer/__data__.py:197
msgid "Failed while executing pre-install modules."
msgstr ""
"Ошибка при выполнении предварительно установленных модулей."

#: viewer/__data__.py:198
msgid "Failed to create disklabel on IPR RAID."
msgstr ""
"Не удалось создать метку диска в IPR RAID."

#: viewer/__data__.py:199
msgid "Failed to execute install automation pre-script."
msgstr ""
"Не удалось выполнить предварительный сценарий автоматизации установки."

#: viewer/__data__.py:200
msgid "Failed to execute PowerKVM pre-script."
msgstr ""
"Не удалось выполнить предварительный сценарий PowerKVM."

#: viewer/__data__.py:201
msgid "Failed while executing post-install modules."
msgstr ""
"Ошибка при выполнении модулей после установки."

#: viewer/__data__.py:202
msgid "Failed to set password."
msgstr ""
"Не удалось задать пароль."

#: viewer/__data__.py:203
msgid "Failed to execute install automation post-script."
msgstr ""
"Не удалось выполнить сценарий после автоматической установки."

#: viewer/__data__.py:204
msgid "Failed to set NTP service."
msgstr ""
"Не удалось задать службу NTP."

#: viewer/__data__.py:205
msgid "Invalid network interface."
msgstr ""
"Недопустимый сетевой интерфейс."

#: viewer/__data__.py:206
msgid "Failed to write UTC time configuration."
msgstr ""
"Не удалось записать конфигурацию времени UTC."

#: viewer/__data__.py:207
msgid "Missing target network interface in install automation file."
msgstr ""
"В файле автоматизации установки отсутствует целевой сетевой интерфейс."

#: viewer/__data__.py:208
msgid "Missing target disk parameter in install automation file."
msgstr ""
"В файле автоматизации установки отсутствует параметр целевого диска."

#: viewer/__data__.py:209
msgid "Error while installing packages."
msgstr ""
"Ошибка при установке пакетов."

#: viewer/__data__.py:210
msgid "No repository provided to the installer."
msgstr ""
"Для программы установки не указано хранилище."

#: viewer/__data__.py:211
msgid "Invalid repository path."
msgstr ""
"Недопустимый путь к хранилищу."

#: viewer/__data__.py:212
msgid "Invalid repository content."
msgstr ""
"Недопустимое содержимое хранилища."

#: viewer/__data__.py:213
msgid "Failed to load Timezones list."
msgstr ""
"Не удалось загрузить список часовых поясов."

#: viewer/__data__.py:214
msgid "Firmware version must be greater than %s"
msgstr ""
"Версия встроенного ПО должна быть выше %s"

#: viewer/__data__.py:215
msgid "Invalid machine type."
msgstr ""
"Недопустимый тип системы."

#: viewer/__data__.py:216
msgid "Invalid hypervisor."
msgstr ""
"Недопустимый гипервизор."

#: viewer/__data__.py:217
msgid "No previous system found."
msgstr ""
"Не найдена предыдущая система."

#: viewer/__data__.py:218
msgid "Unexpected error while partitioning the disk."
msgstr ""
"Непредвиденная ошибка во время создания разделов диска."

#: viewer/__data__.py:219
msgid "Unexpected error while installing packages."
msgstr ""
"Непредвиденная ошибка при установке пакетов."

#: viewer/__data__.py:220
msgid "Unexpected error while executing post-install modules."
msgstr ""
"Непредвиденная ошибка при выполнении модулей после установки."

#: viewer/__data__.py:221
msgid "Unexpected error while executing kickstart."
msgstr ""
"Непредвиденная ошибка при выполнении kickstart."

#: viewer/__data__.py:222
msgid "Unexpected error while verifying disks."
msgstr ""
"Непредвиденная ошибка во время проверки дисков."

#: viewer/__data__.py:223
msgid "Unexpected error while selecting disks."
msgstr ""
"Непредвиденная ошибка при выборе дисков."

#: viewer/__data__.py:224
msgid "Unexpected error while configuring system."
msgstr ""
"Непредвиденная ошибка во время настройки системы."

#: viewer/__data__.py:228
msgid "Installation Summary"
msgstr ""
"Краткий обзор установки"

#: viewer/__data__.py:229
msgid "Timezone: "
msgstr ""
"Часовой пояс: "

#: viewer/__data__.py:230
msgid "Date/Time: "
msgstr ""
"Дата/Время: "

#: viewer/__data__.py:231
msgid "NTP servers"
msgstr ""
"Серверы NTP"

#: viewer/__data__.py:232
msgid "NTP disabled"
msgstr ""
"NTP отключен"

#: viewer/__data__.py:233
msgid "IP Address: "
msgstr ""
"IP-адрес: "

#: viewer/__data__.py:234
msgid "Gateway: "
msgstr ""
"Шлюз: "

#: viewer/__data__.py:235
msgid "Netmask: "
msgstr ""
"Маска сети: "

#: viewer/__data__.py:236
msgid "Hostname: "
msgstr ""
"Имя хоста: "

#: viewer/__data__.py:237
msgid "Bridge: "
msgstr ""
"Мост: "

#: viewer/__data__.py:238
msgid "DHCP is enabled"
msgstr ""
"DHCP включен"

#: viewer/__data__.py:239
msgid "Network"
msgstr ""
"Сеть"

#: viewer/__data__.py:240
msgid "Device: "
msgstr ""
"Устройство: "

#: viewer/__data__.py:241
msgid "Password is set"
msgstr ""
"Пароль задан"

#: viewer/__data__.py:242
msgid "System clock uses UTC: "
msgstr ""
"Системные часы используют UTC: "

#: viewer/__data__.py:245
msgid "I Accept both IBM and non-IBM terms"
msgstr ""
"Я принимаю условия IBM и других фирм"

#: viewer/__data__.py:246
msgid "I do not accept the terms in the license agreement"
msgstr ""
"Я не принимаю условия лицензионного соглашения"


# ENGL1SH_VERS10N 49670_14 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 228
# T9N_SH1P_STR1NG KVM21AAP001 6
