# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR ORGANIZATION
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"POT-Creation-Date: 2014-05-08 13:49+BRT\n"
"PO-Revision-Date: 2014-05-08 13:50-0300\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: UTF-8\n"
"Generated-By: pygettext.py 1.5\n"


#: controller/__data__.py:7
msgid "ERROR: Cannot detect installed system, impossible to upgrade"
msgstr ""

#: controller/__data__.py:8
msgid "ERROR: Cannot detect installed system version, impossible to upgrade"
msgstr ""

#: controller/__data__.py:9
msgid "ERROR: Cannot fast forward upgrades, impossible to upgrade"
msgstr ""

#: controller/__data__.py:10
msgid "ERROR: Installed system is newer, impossible to upgrade"
msgstr ""

#: controller/__data__.py:11
msgid "ERROR: Upgrade failed."
msgstr ""

#: controller/__data__.py:12
msgid "Error while installing IBM PowerKVM into disk %s"
msgstr ""

#: controller/__data__.py:13
msgid "Formatting disks..."
msgstr ""

#: controller/__data__.py:14
msgid "Formatting root device to reinstall system"
msgstr ""

#: controller/__data__.py:15
msgid "Installing IBM PowerKVM into disk %s..."
msgstr ""

#: controller/__data__.py:16
msgid "Install IBM PowerKVM"
msgstr ""

#: controller/__data__.py:17
msgid "Proceed to upgrade the system?"
msgstr ""

#: controller/__data__.py:18
msgid "Reinstall IBM PowerKVM"
msgstr ""

#: controller/__data__.py:19
msgid "Rescue mode (goes to terminal)"
msgstr ""

#: controller/__data__.py:20
msgid "Running Post Upgrade Scripts"
msgstr ""

#: controller/__data__.py:21
msgid "System Installed. Starting post install scripts."
msgstr ""

#: controller/__data__.py:22
msgid "Upgrade concluded!"
msgstr ""

#: controller/__data__.py:23
msgid "Upgrade installed IBM PowerKVM"
msgstr ""

#: controller/__data__.py:24
msgid "Getting disk information..."
msgstr ""

#: ui/__data__.py:6 viewer/__data__.py:36
msgid "Root Password"
msgstr ""

#: ui/__data__.py:7
msgid "Timezone selection"
msgstr ""

#: ui/__data__.py:8
msgid "Date and Time"
msgstr ""

#: ui/__data__.py:9
msgid "Configure Network"
msgstr ""

#: ui/__data__.py:10
msgid "DNS configuration"
msgstr ""

#: ui/__data__.py:11
msgid "Exit"
msgstr ""

#: viewer/__data__.py:12
msgid "Welcome to IBM PowerKVM %s"
msgstr ""

#: viewer/__data__.py:13
msgid "Select one of the options below and follow the instructions."
msgstr ""

#: viewer/__data__.py:14
msgid ""
"Are you sure you want to install on device %s?\n\n The following partitions will be removed: %s\n\n The following LVMs will be removed: %s\n\n"
msgstr ""

#: viewer/__data__.py:17
msgid "IBM PowerKVM %s"
msgstr ""

#: viewer/__data__.py:18
msgid "Ok"
msgstr ""

#: viewer/__data__.py:19
msgid "Back"
msgstr ""

#: viewer/__data__.py:20
msgid "Skip"
msgstr ""

#: viewer/__data__.py:21
msgid "Next"
msgstr ""

#: viewer/__data__.py:22
msgid "Edit"
msgstr ""

#: viewer/__data__.py:23
msgid "  <Tab>/<Shift-Tab> between elements   |  <Space> selects"
msgstr ""

#: viewer/__data__.py:29
msgid "Password Length"
msgstr ""

#: viewer/__data__.py:30
msgid "The root password must be at least 6 characters long."
msgstr ""

#: viewer/__data__.py:31
msgid "Password Mismatch"
msgstr ""

#: viewer/__data__.py:32
msgid "The passwords you entered were different. Please try again."
msgstr ""

#: viewer/__data__.py:33
msgid "Password (confirm):"
msgstr ""

#: viewer/__data__.py:34
msgid "Password:"
msgstr ""

#: viewer/__data__.py:35
msgid "Pick a root password. You must type it twice to ensure you know what it is and didn't make a mistake in typing. Remember that the root password is a critical part of system security!"
msgstr ""

#: viewer/__data__.py:41
msgid "Select the timezone for the system"
msgstr ""

#: viewer/__data__.py:42
msgid "System clock uses UTC"
msgstr ""

#: viewer/__data__.py:43
msgid "Timezone Selection"
msgstr ""

#: viewer/__data__.py:48
msgid "Select the device to be configured:"
msgstr ""

#: viewer/__data__.py:49
msgid "Configure network"
msgstr ""

#: viewer/__data__.py:50
msgid "UP"
msgstr ""

#: viewer/__data__.py:51
msgid "DOWN"
msgstr ""

#: viewer/__data__.py:56
msgid "Hostname"
msgstr ""

#: viewer/__data__.py:57
msgid "Primary DNS"
msgstr ""

#: viewer/__data__.py:58
msgid "Secondary DNS"
msgstr ""

#: viewer/__data__.py:59
msgid "Search"
msgstr ""

#: viewer/__data__.py:60
msgid "DNS Configuration"
msgstr ""

#: viewer/__data__.py:65
msgid "NTP Configuration"
msgstr ""

#: viewer/__data__.py:66
msgid "NTP server 1: "
msgstr ""

#: viewer/__data__.py:67
msgid "NTP server 2: "
msgstr ""

#: viewer/__data__.py:68
msgid "NTP server 3: "
msgstr ""

#: viewer/__data__.py:69
msgid "NTP server 4: "
msgstr ""

#: viewer/__data__.py:70
msgid "Enable"
msgstr ""

#: viewer/__data__.py:75
msgid "Date and time configuration"
msgstr ""

#: viewer/__data__.py:76
msgid "Date (YYYY / MM / DD):"
msgstr ""

#: viewer/__data__.py:77
msgid "Time (HH:MM:SS):"
msgstr ""

#: viewer/__data__.py:78
msgid "Date time error"
msgstr ""

#: viewer/__data__.py:79
msgid ""
"Date or time format is not correct!\nThe input: %s\nCorrect format: YYYY/MM/DD HH:MM:SS"
msgstr ""

#: viewer/__data__.py:85
msgid "Invalid Entry"
msgstr ""

#: viewer/__data__.py:86
msgid "Either DHCP must be selected, or IP must be provided."
msgstr ""

#: viewer/__data__.py:87
msgid "Device"
msgstr ""

#: viewer/__data__.py:88
msgid "MAC Address"
msgstr ""

#: viewer/__data__.py:89
msgid "Use DHCP"
msgstr ""

#: viewer/__data__.py:90
msgid "Static IP"
msgstr ""

#: viewer/__data__.py:91
msgid "Netmask"
msgstr ""

#: viewer/__data__.py:92
msgid "Default gateway IP"
msgstr ""

#: viewer/__data__.py:93
msgid "Network Device Configuration"
msgstr ""

#: viewer/__data__.py:94
msgid "Create Network bridge device (br%s)"
msgstr ""

#: viewer/__data__.py:98
msgid "Error while trying to remove the Volume Group in %s"
msgstr ""

#: viewer/__data__.py:99
msgid "The disk %s is part of the LVM Volume Group(s) ['VolGroup'] which will be destroyed if you continue. Are you sure you want to use that disk?"
msgstr ""

#: viewer/__data__.py:100
msgid "Yes"
msgstr ""

#: viewer/__data__.py:101
msgid "No"
msgstr ""

#: viewer/__data__.py:102
msgid "Installation Error"
msgstr ""

#: viewer/__data__.py:107
msgid "Select the device to install IBM PowerKVM. All data in the selected disk will be lost."
msgstr ""

#: viewer/__data__.py:108
msgid "Disk information"
msgstr ""

#: viewer/__data__.py:109
msgid "  <Tab>/<Shift-Tab> between elements  |  <F3> for details"
msgstr ""

#: viewer/__data__.py:110
msgid "Disk size"
msgstr ""

#: viewer/__data__.py:111
msgid "The disk size must be greater than 70G!"
msgstr ""

#: viewer/__data__.py:112
msgid "No disk found"
msgstr ""

#: viewer/__data__.py:113
msgid "No disks were found in the system."
msgstr ""

#: viewer/__data__.py:114
msgid "ID:"
msgstr ""

#: viewer/__data__.py:115
msgid "Size"
msgstr ""

#: viewer/__data__.py:116
msgid "Multipath:"
msgstr ""

#: viewer/__data__.py:117
msgid "Name"
msgstr ""

#: viewer/__data__.py:118
msgid "Filesystem"
msgstr ""

#: viewer/__data__.py:119
msgid "VG/Raid"
msgstr ""

#: viewer/__data__.py:125
msgid "Choose the language"
msgstr ""

#: viewer/__data__.py:130
msgid "The current installed system will be erased, including all general system-wide and virtualization configuration files.Only the contents within /var/lib/libvirt/images and /var/log will be preserved. WARNING: this means the configuration of your Virtual Machines WILL BE ERASED, leaving only the disk images behind. You are advised to back up your VM configurations before proceeding. Are you sure you would like to proceed?"
msgstr ""

#: viewer/__data__.py:136
msgid ""
"A previous installation of PowerKVM has been detected at:\n"
"\n"
"%s\n"
"\n"
msgstr ""

#: viewer/__data__.py:141
msgid "Hardware is not entitled to proceed. Aborting!"
msgstr ""

#: viewer/__data__.py:142
msgid "Invalid entitlement! "
msgstr ""

#: viewer/__data__.py:147
msgid "Preparing to install IBM PowerKVM System"
msgstr ""

#: viewer/__data__.py:148
msgid "Unknown error"
msgstr ""

#: viewer/__data__.py:149
msgid "Sorry something went wrong the proper error message is on the log file"
msgstr ""

#: viewer/__data__.py:155
msgid "Please, reboot your system now."
msgstr ""

#: viewer/__data__.py:156
msgid "Reboot"
msgstr ""

#: viewer/__data__.py:157
msgid "Installation completed! "
msgstr ""

#: viewer/__data__.py:162
msgid "The reinstall process can't continue. No previous system was found. Aborting!"
msgstr ""

#: viewer/__data__.py:168
msgid "Preparing to upgrade system"
msgstr ""

#: viewer/__data__.py:169
msgid "Working..."
msgstr ""

#: viewer/__data__.py:174
msgid "Installation exited with error code: %s"
msgstr ""

#: viewer/__data__.py:175
msgid "Log is available on %s"
msgstr ""

#: viewer/__data__.py:176
msgid "Unexpected error."
msgstr ""

#: viewer/__data__.py:177
msgid "Unknown error."
msgstr ""

#: viewer/__data__.py:178
msgid "Invalid disk size."
msgstr ""

#: viewer/__data__.py:179
msgid "No disk found in the system."
msgstr ""

#: viewer/__data__.py:180
msgid "Hardware is not entitled, aborting installation."
msgstr ""

#: viewer/__data__.py:181
msgid "Error while installing IBM PowerKVM."
msgstr ""

#: viewer/__data__.py:182
msgid "Error while performing disk operations."
msgstr ""

#: viewer/__data__.py:183
msgid "Invalid error code."
msgstr ""

#: viewer/__data__.py:184
msgid "Could not remove LVM entities."
msgstr ""

#: viewer/__data__.py:185
msgid "Could not deactivate volume groups."
msgstr ""

#: viewer/__data__.py:186
msgid "Could not activate volume groups."
msgstr ""

#: viewer/__data__.py:187
msgid "Could not stop software RAID."
msgstr ""

#: viewer/__data__.py:188
msgid "Disk information not available."
msgstr ""

#: viewer/__data__.py:189
msgid "Problem while removing pratitioning scheme."
msgstr ""

#: viewer/__data__.py:190
msgid "Problem while partitioning the disk."
msgstr ""

#: viewer/__data__.py:191
msgid "Problem while creating LVM."
msgstr ""

#: viewer/__data__.py:192
msgid "Failed to download (HTTP) install automation file."
msgstr ""

#: viewer/__data__.py:193
msgid "Failed to download (TFTP) install automation file."
msgstr ""

#: viewer/__data__.py:194
msgid "Problem downloading (NFS) install automation file."
msgstr ""

#: viewer/__data__.py:195
msgid "Could not parse install automation file."
msgstr ""

#: viewer/__data__.py:196
msgid "Failed to get IPR RAID label."
msgstr ""

#: viewer/__data__.py:197
msgid "Failed while executing pre-install modules."
msgstr ""

#: viewer/__data__.py:198
msgid "Failed to create disklabel on IPR RAID."
msgstr ""

#: viewer/__data__.py:199
msgid "Failed to execute install automation pre-script."
msgstr ""

#: viewer/__data__.py:200
msgid "Failed to execute PowerKVM pre-script."
msgstr ""

#: viewer/__data__.py:201
msgid "Failed while executing post-install modules."
msgstr ""

#: viewer/__data__.py:202
msgid "Failed to set password."
msgstr ""

#: viewer/__data__.py:203
msgid "Failed to execute install automation post-script."
msgstr ""

#: viewer/__data__.py:204
msgid "Failed to set NTP service."
msgstr ""

#: viewer/__data__.py:205
msgid "Invalid network interface."
msgstr ""

#: viewer/__data__.py:206
msgid "Failed to write UTC time configuration."
msgstr ""

#: viewer/__data__.py:207
msgid "Missing target network interface in install automation file."
msgstr ""

#: viewer/__data__.py:208
msgid "Missing target disk parameter in install automation file."
msgstr ""

#: viewer/__data__.py:209
msgid "Error while installing packages."
msgstr ""

#: viewer/__data__.py:210
msgid "No repository provided to the installer."
msgstr ""

#: viewer/__data__.py:211
msgid "Invalid repository path."
msgstr ""

#: viewer/__data__.py:212
msgid "Invalid repository content."
msgstr ""

#: viewer/__data__.py:213
msgid "Failed to load Timezones list."
msgstr ""

#: viewer/__data__.py:214
msgid "Firmware version must be greater than %s"
msgstr ""

#: viewer/__data__.py:215
msgid "Invalid machine type."
msgstr ""

#: viewer/__data__.py:216
msgid "Invalid hypervisor."
msgstr ""

#: viewer/__data__.py:217
msgid "No previous system found."
msgstr ""

#: viewer/__data__.py:218
msgid "Unexpected error while partitioning the disk."
msgstr ""

#: viewer/__data__.py:219
msgid "Unexpected error while installing packages."
msgstr ""

#: viewer/__data__.py:220
msgid "Unexpected error while executing post-install modules."
msgstr ""

#: viewer/__data__.py:221
msgid "Unexpected error while executing kickstart."
msgstr ""

#: viewer/__data__.py:222
msgid "Unexpected error while verifying disks."
msgstr ""

#: viewer/__data__.py:223
msgid "Unexpected error while selecting disks."
msgstr ""

#: viewer/__data__.py:224
msgid "Unexpected error while configuring system."
msgstr ""

#: viewer/__data__.py:228
msgid "Installation Summary"
msgstr ""

#: viewer/__data__.py:229
msgid "Timezone: "
msgstr ""

#: viewer/__data__.py:230
msgid "Date/Time: "
msgstr ""

#: viewer/__data__.py:231
msgid "NTP servers"
msgstr ""

#: viewer/__data__.py:232
msgid "NTP disabled"
msgstr ""

#: viewer/__data__.py:233
msgid "IP Address: "
msgstr ""

#: viewer/__data__.py:234
msgid "Gateway: "
msgstr ""

#: viewer/__data__.py:235
msgid "Netmask: "
msgstr ""

#: viewer/__data__.py:236
msgid "Hostname: "
msgstr ""

#: viewer/__data__.py:237
msgid "Bridge: "
msgstr ""

#: viewer/__data__.py:238
msgid "DHCP is enabled"
msgstr ""

#: viewer/__data__.py:239
msgid "Network"
msgstr ""

#: viewer/__data__.py:240
msgid "Device: "
msgstr ""

#: viewer/__data__.py:241
msgid "Password is set"
msgstr ""

#: viewer/__data__.py:242
msgid "System clock uses UTC: "
msgstr ""

#: viewer/__data__.py:245
msgid "I Accept both IBM and non-IBM terms"
msgstr ""

#: viewer/__data__.py:246
msgid "I do not accept the terms in the license agreement"
msgstr ""

